export const CODE_ERROR_FORBIDDEN = 403;
export const CODE_ERROR_UNAUTHORIZED = 401;
export const CODE_ERROR_NOT_FOUND = 404;
export const CODE_ERROR_UNPROCESSABLE_ENTITY = 422;
export const CODE_ERROR_INTERNAL_SERVER_ERROR = 500;
